# Project name
name: "data_forge_analytics"
version: '1.0.0'

# Profile configuration
profile: "{{ env_var('DBT_PROFILE') }}"
require-dbt-version: "1.12.2"
vars:
  'dbt_date:time_zone': 'America/Los_Angeles'
  db_name: "{{ env_var('PG_DB_NAME') }}"

# Project directories
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories to clean up
clean-targets:
  - "target"
  - "dbt_packages"

# Models materialization strategies
models:
  data_forge_analytics:
    staging:
      +materialized: view
      crm:
        +schema: staging_crm
      erp:
        +schema: staging_erp
      ops:
        +schema: staging_ops

    intermediate:
      +materialized: view
      ordering:
        +schema: inter_ordering
      shipping:
        +schema: inter_shipping

    marts:
      +materialized: table
      ordering:
        +schema: mart_ordering

# Snapshot models configuration
snapshots:
  data_forge_analytics:
    ordering:
      +target_database: "{{ env_var('PG_DB_NAME') }}"
      +target_schema: "{{ env_var('PG_SNAPSHOT_SCHEMA') }}"
