services:
  dbt:
    platform: linux/amd64
    image: fanihabte/base-dbt-postgres:1.0.1
    volumes:
      - .:/usr/app/dbt
      - dbt-packages:/opt/dbt_packages
    env_file:
      - ${ENV_FILE:-.env}

volumes:
  dbt-packages:
