name: "ERAE dbt"
on:
  pull_request:
  push:
    branches: [ 'main' ]

jobs:
  build:
    name: Build and test dbt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: extractions/setup-just@v3
      - run: just ci

      - if: always()
        run: just down

  deploy:
    name: Deploy to prod
    needs: build
    if: github.event_name == 'push'
    runs-on: [ self-hosted, linux, x64 ]
    timeout-minutes: 10

    steps:
    - name: Run dbt locally
      env:
        PROJECT_DIR: ${{ secrets.PROJECT_DIR }}
      run: |
        cd "$PROJECT_DIR"
        git fetch origin main && git reset --hard origin/main
        docker compose run --rm dbt deps
        docker compose run --rm dbt build
