name: "ERAE Dbt"
on:
  pull_request:
  push:
    branches: ['main']

env:
  COMPOSE: docker compose --env-file .env.ci -f docker-compose.yml -f docker-compose.ci.yml

jobs:
  build:
    name: Build & Test DBT
    runs-on: ubuntu-latest

    steps:
      - name: Pull git repo
        uses: actions/checkout@v4

      - name: Install Just
        uses: extractions/setup-just@v2

      - name: Install dbt dependencies
        run: |
          just deps

      - name: Parse
        run: |
          just parse

      - if: always()
        run: $COMPOSE down -v